import React, { useMemo, useState } from 'react';
import { Download, FileUp, Radar } from 'lucide-react';
import { Button } from '../../components/atoms/Button';
import { Pill } from '../../components/atoms/Badge';
import { Banner, Card, Drawer, KpiRow, KpiTile, PageHead, SampleTag, Td, Th, Tile } from '../../components/molecules/Page';
import { Modal } from '../../components/molecules/Modal';
import { FLEET, STATIONS, TENANTS, tenantOf } from '../../data/fleet';
import { satElements } from '../../orbit/fleetOrbit';
import { periodMinutes } from '../../orbit/orbit';
import { parseTle, tleFromElements } from '../../orbit/sgp4';
import { parseCdm } from '../../orbit/cdm';
import { satContacts } from '../../orbit/contacts';
import { aboveThreshold, Cdm, useConjunctionStore } from '../../ops/conjunctionStore';
import { useAuthStore } from '../../store/useAuthStore';
import { useMissionStore } from '../../store/useMissionStore';
import { stateFn, useOrbitStore } from '../../store/useOrbitStore';
import { saveBlob } from '../../store/useDeliveryStore';
import { toast } from '../../store/useToastStore';
import { hm, inputCls, RoleLink, selectCls, useHashParams, utc } from './shared';
import { Select } from '../../components/molecules/Select';

/** Flight dynamics decisions (thresholds, screening) sit with these roles. ponytail: local rule until policy.ts has an 'fd:edit' action. */
const FD_ROLES = ['Flight Director', 'Flight Engineer'];
const PC_STEPS = [1e-3, 1e-4, 1e-5, 1e-6, 1e-7];
const pcText = (p: number) => (p === 0 ? '0' : p.toExponential(1).replace('e', '×10^').replace('^-', '⁻').replace(/\d+$/, (d) => [...d].map((c) => '⁰¹²³⁴⁵⁶⁷⁸⁹'[+c]).join('')));
const dist = (m: number) => (Math.abs(m) >= 1000 ? `${(m / 1000).toFixed(2)} km` : `${Math.round(m)} m`);
const ageText = (ms: number) => { const h = ms / 3600_000; return h < 48 ? `${h.toFixed(0)} h` : `${(h / 24).toFixed(1)} d`; };

function oem(satId: string, fromTle: boolean): string {
  const at = stateFn(satId);
  const t0 = Math.floor(Date.now() / 60_000) * 60_000, step = 5 * 60_000, n = 288;
  const iso = (ms: number) => new Date(ms).toISOString().replace('Z', '');
  const lines = [
    'CCSDS_OEM_VERS = 2.0',
    `COMMENT Generated by VYUH console from ${fromTle ? 'SGP4 on the ingested TLE (TEME frame)' : 'the console two-body + J2 model; kilometre-level error, SAMPLE quality'}`,
    `CREATION_DATE = ${iso(Date.now())}`, 'ORIGINATOR = VYUH-MCS', '', 'META_START',
    `OBJECT_NAME = ${satId}`, `OBJECT_ID = ${satId}`, 'CENTER_NAME = EARTH', `REF_FRAME = ${fromTle ? 'TEME' : 'EME2000'}`, 'TIME_SYSTEM = UTC',
    `START_TIME = ${iso(t0)}`, `STOP_TIME = ${iso(t0 + n * step)}`, 'META_STOP', '',
  ];
  for (let i = 0; i <= n; i++) {
    const s = at(t0 + i * step);
    lines.push([iso(t0 + i * step), ...s.eci.map((v) => (v / 1000).toFixed(6)), ...s.velEci.map((v) => (v / 1000).toFixed(9))].join(' '));
  }
  return lines.join('\n') + '\n';
}

/** S31 · Orbits and conjunctions: TLE ingest and SGP4, OEM export, CDM inbox with per-mission Pc threshold, manoeuvre screening requests. */
export const Orbits: React.FC<{ onNavigate: (to: string) => void }> = ({ onNavigate }) => {
  const user = useAuthStore((s) => s.user);
  const role = useAuthStore((s) => s.activeRole);
  const mayFd = FD_ROLES.includes(role) ? { allowed: true as const, reason: undefined } : { allowed: false as const, reason: `${role} cannot do this. Requires Flight Director or Flight Engineer.` };
  const [q, setQ] = useHashParams();
  const satId = FLEET.some((s) => s.sat_id === q.sat) ? q.sat : 'AKV-03';
  const { tles, ingest, remove } = useOrbitStore();
  const { cdms, thresholds, addCdm, setThreshold, setCdm } = useConjunctionStore();
  const tle = tles[satId];
  const [text, setText] = useState('');
  const [errs, setErrs] = useState<string[]>([]);
  const [cdmText, setCdmText] = useState('');
  const [cdmErrs, setCdmErrs] = useState<string[]>([]);
  const [closing, setClosing] = useState<Cdm | null>(null);
  const [closeWhy, setCloseWhy] = useState('');

  const now = Date.now();
  const parsed = tle ? parseTle(tle.text).tle : undefined;
  const age = parsed ? now - parsed.epochMs : 0;
  const st = useMemo(() => { try { return stateFn(satId)(now); } catch { return null; } }, [satId, tle?.ingestedAt, Math.floor(now / 10_000)]); // eslint-disable-line react-hooks/exhaustive-deps
  const period = parsed ? 1440 / parsed.revPerDay : periodMinutes(satElements(FLEET.find((s) => s.sat_id === satId)!).a);
  const next = satContacts(satId, now, 24 * 3600_000).filter((c) => c.aos > now && STATIONS.find((s) => s.id === c.station)?.state !== 'MAINTENANCE').slice(0, 3);
  const sel = cdms.find((c) => c.messageId === q.cdm);
  const open = cdms.filter((c) => c.status !== 'CLOSED');
  const above = open.filter((c) => aboveThreshold(c, thresholds));
  const mission = tenantOf(satId);

  const audit = (sat: string, what: string, summary: string) => useMissionStore.getState().appendAudit({
    timestamp_utc: new Date().toISOString(), operator_id: user.id, operator_name: user.name, sat_id: sat, command_mnemonic: what,
    procedure_id: '—', procedure_version: '—', sequence_count: 0, result: 'ACK', params_summary: summary,
  });
  const doIngest = (raw: string, sample: boolean) => {
    const p = parseTle(raw);
    if (!p.tle) { setErrs(p.errors); return; }
    ingest({ satId, text: raw.trim(), ingestedAt: Date.now(), by: user.name, sample });
    audit(satId, 'TLE_INGEST', `catalogue ${p.tle.catnr}, epoch ${new Date(p.tle.epochMs).toISOString()}`);
    setErrs([]); setText('');
    toast.success(`TLE ingested for ${satId}`, { body: 'Passes and positions now come from SGP4.' });
  };
  const doCdm = (raw: string) => {
    const p = parseCdm(raw);
    if (!p.cdm) { setCdmErrs(p.errors); return; }
    addCdm(p.cdm); setCdmErrs([]); setCdmText('');
    audit(p.cdm.satId, 'CDM_INGEST', `${p.cdm.messageId}: Pc ${p.cdm.pc.toExponential(1)}, miss ${dist(p.cdm.missM)}`);
    setQ({ cdm: p.cdm.messageId });
  };
  const requestScreening = (c: Cdm) => {
    setCdm(c.messageId, { status: 'SCREENING', screening: { requestedBy: user.name, at: Date.now() } });
    audit(c.satId, 'MANOEUVRE_SCREEN', `${c.messageId}: screening requested for ${c.satId} vs ${c.objectName}`);
    window.setTimeout(() => {
      const after = Math.max(c.pc / 800, 1e-8);
      useConjunctionStore.getState().setCdm(c.messageId, { status: 'SCREENED', screening: { requestedBy: user.name, at: Date.now(), result: `Candidate burn 0.12 m/s along-track at TCA − 1.5 orbits: miss grows to ${dist(c.missM * 9.5)}, Pc ${after.toExponential(1)}; no new conjunctions in 72 h.` } });
    }, 3000);
  };

  return (
    <>
      <PageHead crumb="Plan / Orbits and conjunctions" title="Orbits and conjunctions" sub="Orbit data per satellite, conjunction data messages and manoeuvre screening"
        actions={<label className={`${selectCls} flex items-center gap-2`}><span className="text-[#7C8594]">Satellite</span>
          <Select value={satId} onChange={(e) => setQ({ sat: e.target.value })} className="bg-transparent outline-none">{FLEET.map((s) => <option key={s.sat_id} className="bg-[#11141B]">{s.sat_id}</option>)}</Select></label>} />

      <KpiRow>
        <KpiTile value={tle ? ageText(age) : 'Model'} label="Orbit source" sub={tle ? `TLE epoch age${tle.sample ? ' · sample TLE' : ''}` : 'two-body + J2, no TLE yet'} tone={!tle ? 'plain' : age > 7 * 86400_000 ? 'crit' : age > 3 * 86400_000 ? 'warn' : 'ok'} />
        <KpiTile value={open.length} label="Open conjunction messages" sub="all satellites" />
        <KpiTile value={above.length} label="At or above threshold" sub="raise an alarm" tone={above.length ? 'crit' : 'ok'} />
        <KpiTile value={pcText(thresholds[mission] ?? 1e-4)} label={`Pc threshold · ${mission}`} sub="action threshold" />
      </KpiRow>

      <div className="flex flex-wrap gap-4 items-start">
        <div className="flex-[999_1_560px] min-w-0">
          <Card title={`Orbit data · ${satId}`} actions={tle ? <Pill tone="ok">SGP4 on TLE</Pill> : <SampleTag>Model elements</SampleTag>}>
            <div className="flex flex-col gap-4">
              {tle && age > 3 * 86400_000 && <Banner kind={age > 7 * 86400_000 ? 'crit' : 'warn'} lead={`TLE is ${ageText(age)} old.`}>Prediction error grows with age; ingest a fresher element set before booking passes.</Banner>}
              <div className="grid gap-2.5" style={{ gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))' }}>
                {[['Altitude', st ? `${st.altKm.toFixed(0)} km` : '—'], ['Latitude', st ? `${st.lat.toFixed(2)}°` : '—'], ['Longitude', st ? `${st.lon.toFixed(2)}°` : '—'], ['Speed', st ? `${st.speedKms.toFixed(2)} km/s` : '—'], ['Period', `${period.toFixed(1)} min`], ['Inclination', parsed ? `${parsed.inclDeg.toFixed(2)}°` : `${FLEET.find((s) => s.sat_id === satId)!.inclination_deg.toFixed(2)}°`]].map(([k, v]) => (
                  <Tile key={k}><span className="block text-[12px] text-[#7C8594]">{k}</span><span className="font-mono-code text-[15px]">{v}</span></Tile>
                ))}
              </div>
              {tle && <div className="text-[12.5px] text-[#9AA3B2]">Ingested {utc(tle.ingestedAt)} by {tle.by}{parsed ? `, epoch ${utc(parsed.epochMs)}` : ''}.<pre className="mt-2 font-mono-code text-[11.5px] text-[#C9CED6] bg-[#161A22] rounded-lg p-3 overflow-x-auto">{tle.text}</pre></div>}
              <label className="flex flex-col gap-1.5 text-[12px] text-[#7C8594]">Paste a two- or three-line element set
                <textarea value={text} onChange={(e) => setText(e.target.value)} rows={3} spellCheck={false} placeholder={'1 90003U 26001A   26277.50000000  .00000000  00000-0  10000-3 0  9994\n2 90003  97.5000 303.3358 0010000 212.1401 321.9021 15.15322385    16'} className={`${inputCls} h-auto py-2 font-mono-code text-[12px]`} />
              </label>
              {errs.length > 0 && <Banner kind="crit" lead="TLE refused.">{errs.join(' ')}</Banner>}
              <div className="flex flex-wrap gap-2">
                <Button disabled={!mayFd.allowed || !text.trim()} reason={mayFd.reason} onClick={() => doIngest(text, false)}>Ingest TLE</Button>
                <Button variant="secondary" disabled={!mayFd.allowed} onClick={() => setText(tleFromElements(satId, 90000 + FLEET.findIndex((s) => s.sat_id === satId), satElements(FLEET.find((s) => s.sat_id === satId)!), now))}>Fill sample TLE</Button>
                {tle && <Button variant="ghost" disabled={!mayFd.allowed} onClick={() => { remove(satId); audit(satId, 'TLE_REMOVE', 'back to model elements'); }}>Use model elements</Button>}
                <Button variant="secondary" onClick={() => saveBlob(new Blob([oem(satId, !!tle)], { type: 'text/plain' }), `${satId}_${new Date(now).toISOString().slice(0, 10)}${tle ? '' : '_SAMPLE'}.oem`)}><Download size={14} /> Export OEM, 24 h</Button>
              </div>
              <div className="flex flex-col gap-1 text-[13px]">
                <span className="text-[12px] text-[#7C8594]">Next passes ({tle ? 'SGP4' : 'model'})</span>
                {next.map((c) => <span key={c.id} className="flex gap-3"><span className="font-mono-code w-12">{c.station}</span><span className="font-mono-code text-[#C9CED6]">{utc(c.aos, false)}–{hm(c.los)}</span><span className="text-[#7C8594]">{c.maxEl}°</span></span>)}
                {next.length === 0 && <span className="text-[#7C8594]">None in the next 24 h.</span>}
                <RoleLink to={`schedule?sat=${satId}`} onNavigate={onNavigate}>Contact schedule for {satId}</RoleLink>
              </div>
            </div>
          </Card>
        </div>

        <div className="flex-[1_1_320px] min-w-0 flex flex-col gap-4">
          <Card title="Collision probability threshold">
            <div className="flex flex-col gap-3 text-[13px]">
              <p className="text-[12.5px] text-[#9AA3B2]">A conjunction at or above its mission's Pc raises a critical alarm. ESA acts at 10⁻⁴; some operators go to 10⁻⁷.</p>
              {TENANTS.map((t) => (
                <label key={t} className="flex items-center justify-between gap-3">{t}
                  <Select value={thresholds[t] ?? 1e-4} disabled={!mayFd.allowed} onChange={(e) => { setThreshold(t, +e.target.value); audit('—', 'PC_THRESHOLD', `${t}: ${(+e.target.value).toExponential(0)}`); }} className={`${selectCls} font-mono-code`}>
                    {PC_STEPS.map((p) => <option key={p} value={p} className="bg-[#11141B]">{pcText(p)}</option>)}
                  </Select>
                </label>
              ))}
              {!mayFd.allowed && <span className="text-[12.5px] text-[#9AA3B2]">{mayFd.reason}</span>}
            </div>
          </Card>
          <Card title="Import a CDM" actions={<SampleTag>3 sample CDMs loaded</SampleTag>}>
            <div className="flex flex-col gap-2.5">
              <textarea value={cdmText} onChange={(e) => setCdmText(e.target.value)} rows={4} spellCheck={false} placeholder="CCSDS_CDM_VERS = 1.0 …  (KVN)" aria-label="CDM text" className={`${inputCls} h-auto py-2 font-mono-code text-[12px]`} />
              {cdmErrs.length > 0 && <Banner kind="crit" lead="CDM refused.">{cdmErrs.join(' ')}</Banner>}
              <div className="flex flex-wrap gap-2">
                <Button size="sm" disabled={!cdmText.trim()} onClick={() => doCdm(cdmText)}>Import</Button>
                <label className="inline-flex items-center gap-1.5 h-8 px-3 rounded-[10px] bg-[#171B24] border border-[#232936] text-[12.5px] cursor-pointer hover:bg-[#1D222D]"><FileUp size={14} /> Upload file
                  <input type="file" accept=".cdm,.txt,.kvn" className="sr-only" onChange={(e) => { const f = e.target.files?.[0]; if (f) f.text().then(doCdm); e.target.value = ''; }} /></label>
              </div>
              <p className="text-[12px] text-[#7C8594]">Space-Track and TraCSS feeds are not connected yet; messages arrive by paste or upload.</p>
            </div>
          </Card>
        </div>
      </div>

      <div className="mt-4">
        <Card title="Conjunction inbox" actions={<RoleLink to="alarms" onNavigate={onNavigate}>Alarm console</RoleLink>}>
          <div className="-mx-5 overflow-x-auto">
            <table className="w-full min-w-[820px] border-collapse">
              <thead><tr><Th>TCA</Th><Th>Satellite</Th><Th>Object</Th><Th>Miss distance</Th><Th>Pc</Th><Th>Status</Th><Th>Source</Th></tr></thead>
              <tbody>
                {[...cdms].sort((a, b) => a.tcaMs - b.tcaMs).map((c) => {
                  const hot = aboveThreshold(c, thresholds);
                  return (
                    <tr key={c.messageId} onClick={() => setQ({ cdm: c.messageId })} className={`cursor-pointer ${c.messageId === q.cdm ? 'bg-[#1B2130]' : 'hover:bg-[#141821]'} ${c.status === 'CLOSED' ? 'opacity-60' : ''}`}>
                      <Td className="font-mono-code text-[12.5px]"><button type="button" className="text-left" onClick={(e) => { e.stopPropagation(); setQ({ cdm: c.messageId }); }}>{utc(c.tcaMs)}</button></Td>
                      <Td className={`font-mono-code ${c.satId === satId ? 'text-[#F2A65A]' : ''}`}>{c.satId}</Td>
                      <Td>{c.objectName} <span className="text-[12px] text-[#7C8594]">{c.objectId}</span></Td>
                      <Td className="font-mono-code">{dist(c.missM)}</Td>
                      <Td><Pill tone={hot ? 'crit' : 'neutral'} className="font-mono-code">{pcText(c.pc)}</Pill></Td>
                      <Td><Pill tone={c.status === 'NEW' ? (hot ? 'action' : 'info') : c.status === 'SCREENED' ? 'ok' : c.status === 'SCREENING' ? 'violet' : 'neutral'}>{c.status === 'NEW' ? (hot ? 'Needs a decision' : 'New') : c.status === 'SCREENING' ? 'Screening' : c.status === 'SCREENED' ? 'Screened' : 'Closed'}</Pill></Td>
                      <Td className="text-[12px] text-[#9AA3B2]">{c.originator}{c.sample && <SampleTag className="ml-2">Sample</SampleTag>}</Td>
                    </tr>
                  );
                })}
                {cdms.length === 0 && <tr><Td colSpan={7} className="text-[#7C8594]">No conjunction messages. Import one above.</Td></tr>}
              </tbody>
            </table>
          </div>
        </Card>
      </div>

      {sel && (
        <Drawer title={`${sel.satId} × ${sel.objectName}`} onClose={() => setQ({ cdm: undefined })}
          footer={<>
            <Button variant="ghost" onClick={() => saveBlob(new Blob([sel.raw], { type: 'text/plain' }), `${sel.messageId}.cdm`)}><Download size={14} /> CDM</Button>
            {sel.status !== 'CLOSED' && <Button variant="secondary" disabled={!mayFd.allowed} onClick={() => { setClosing(sel); setCloseWhy(''); }}>Close event</Button>}
            {(sel.status === 'NEW') && <Button disabled={!mayFd.allowed} reason={mayFd.reason} onClick={() => requestScreening(sel)}><Radar size={14} /> Request manoeuvre screening</Button>}
          </>}>
          {sel.sample && <SampleTag>Sample CDM, not from Space-Track</SampleTag>}
          {aboveThreshold(sel, thresholds) && <Banner kind="crit" lead="Above threshold.">Pc {pcText(sel.pc)} is at or above {tenantOf(sel.satId)}'s {pcText(thresholds[tenantOf(sel.satId)] ?? 1e-4)}. A critical conjunction alarm is raised.</Banner>}
          <div className="grid grid-cols-2 gap-2.5">
            <Tile><span className="block text-[12px] text-[#7C8594]">Time of closest approach</span><span className="font-mono-code text-[15px]">{utc(sel.tcaMs)}</span><span className="block text-[12px] text-[#7C8594]">in {ageText(Math.max(0, sel.tcaMs - now))}</span></Tile>
            <Tile><span className="block text-[12px] text-[#7C8594]">Miss distance</span><span className="text-[26px] font-semibold">{dist(sel.missM)}</span></Tile>
            <Tile><span className="block text-[12px] text-[#7C8594]">Collision probability</span><span className="text-[22px] font-semibold font-mono-code">{pcText(sel.pc)}</span></Tile>
            <Tile><span className="block text-[12px] text-[#7C8594]">Relative speed</span><span className="font-mono-code text-[15px]">{(sel.relSpeedMs / 1000).toFixed(2)} km/s</span></Tile>
          </div>
          <div className="flex flex-col gap-2">
            <span className="text-[13px] text-[#C9CED6]">Relative position at TCA</span>
            {([['Radial', sel.r], ['In-track', sel.t], ['Cross-track', sel.n]] as const).map(([k, v]) => {
              const max = Math.max(Math.abs(sel.r), Math.abs(sel.t), Math.abs(sel.n), 1);
              return (
                <div key={k} className="grid grid-cols-[90px_1fr_80px] items-center gap-2 text-[12.5px]">
                  <span className="text-[#9AA3B2]">{k}</span>
                  <span className="relative h-2 rounded bg-[#161A22]"><span className="absolute top-0 bottom-0 rounded bg-[#6CB8FF]" style={{ left: v < 0 ? `${50 - (Math.abs(v) / max) * 50}%` : '50%', width: `${(Math.abs(v) / max) * 50}%` }} /><span className="absolute top-[-2px] bottom-[-2px] left-1/2 w-px bg-[#3A4252]" /></span>
                  <span className="font-mono-code text-right">{dist(v)}</span>
                </div>
              );
            })}
          </div>
          <dl className="grid grid-cols-2 gap-x-4 gap-y-2.5 text-[13px]">
            {[['Object', `${sel.objectName} (${sel.objectId})`], ['Object type', sel.objectType], ['Message', sel.messageId], ['Originator', sel.originator], ['Received', utc(sel.receivedAt)], ['Mission', tenantOf(sel.satId)]].map(([k, v]) => <div key={k}><dt className="text-[12px] text-[#7C8594]">{k}</dt><dd className="font-mono-code text-[12.5px] break-all">{v}</dd></div>)}
          </dl>
          {sel.screening && <Banner kind={sel.status === 'SCREENED' ? 'ok' : 'info'} lead={sel.status === 'SCREENED' ? 'Screening result.' : 'Screening requested.'}>{sel.screening.result ?? `By ${sel.screening.requestedBy} at ${hm(sel.screening.at)}. Waiting for flight dynamics.`}{sel.screening.result && <SampleTag className="ml-2">Simulated FD answer</SampleTag>}</Banner>}
          {!mayFd.allowed && <p className="text-[12.5px] text-[#9AA3B2]">{mayFd.reason}</p>}
          <div className="flex flex-col gap-1.5">
            <RoleLink to={`satellite?sat=${sel.satId}`} onNavigate={onNavigate}>Open {sel.satId}</RoleLink>
            <RoleLink to="alarms" onNavigate={onNavigate}>Alarm console</RoleLink>
          </div>
        </Drawer>
      )}

      {closing && (
        <Modal title="Close this conjunction event?" onClose={() => setClosing(null)}
          footer={<><Button variant="secondary" autoFocus onClick={() => setClosing(null)}>Keep open</Button>
            <Button variant="danger" disabled={closeWhy.trim().length < 5} onClick={() => { setCdm(closing.messageId, { status: 'CLOSED' }); audit(closing.satId, 'CDM_CLOSE', `${closing.messageId}: ${closeWhy.trim()}`); setClosing(null); }}>Close event</Button></>}>
          <p className="text-[13.5px] text-[#C9CED6]">Closing removes the alarm for {closing.satId} × {closing.objectName}. Record why.</p>
          <input value={closeWhy} onChange={(e) => setCloseWhy(e.target.value)} placeholder="e.g. Updated CDM shows Pc below threshold" aria-label="Reason" className={inputCls} />
        </Modal>
      )}
    </>
  );
};
