// Generates src/styles/light.generated.css: light-theme overrides for every hard-coded
// Tailwind colour class (bg-[#hex], text-[#hex]/50, hover:border-[#hex] ...) used in src/.
// Re-run after adding new colour classes:  npm run gen:light
const fs = require('fs'), path = require('path');

// dark hex -> light hex. Anything not listed (teal accent, status fills) is left as is.
const MAP = {
  '0A1018': 'F6F7F9', '070C12': 'EEF0F3', '05090E': 'EEF0F3', '0E151F': 'F2F4F7', '101823': 'F2F4F7', '111A25': 'FFFFFF',
  '142030': 'F7F8FA', '152131': 'F2F4F7', '16222F': 'F2F4F7', '172434': 'F2F4F7', '1A2738': 'EEF0F3', '1F2D40': 'EAECF0',
  '213044': 'E4E7EC', '2A3B52': 'D5D9E0', '30435B': 'C7CCD6', '3E5370': 'AEB4C0', '3A4E68': 'D0D5DD', '2C3E55': 'D0D5DD',
  '1D2B3C': 'E4E7EC', 'E6EDF3': '101828', 'C9D4E0': '344054', 'CCD6E2': '344054', 'A3B1C2': '475467', '8496AB': '667085',
  '6E7F95': '7A8496', '5F7087': '98A2B3',
  // status / accent colours used as text or thin marks need more contrast on white
  '4DACFF': '1B5FC1', 'FCE83A': '8A6100', 'FF3838': 'C8102E', '56F000': '2A7A12', '2DCCFF': '0B7FA8', 'D42C2C': 'C8102E',
  'C77DDB': '9333EA', '9C9AEC': '6D28D9', '8B7CF6': '7C3AED',
};

const files = [];
(function walk(d) {
  for (const f of fs.readdirSync(d, { withFileTypes: true })) {
    const p = path.join(d, f.name);
    if (f.isDirectory()) walk(p);
    else if (/\.(tsx?)$/.test(f.name)) files.push(p);
  }
})('src');

const RE = /((?:[a-z-]+:)*)(bg|text|border|from|via|to|ring|divide)-\[#([0-9A-Fa-f]{6})\](?:\/(\d+|\[[0-9.]+\]))?/g;
const seen = new Map();
for (const f of files) {
  const s = fs.readFileSync(f, 'utf8');
  for (const m of s.matchAll(RE)) seen.set(m[0], m);
}

const rgb = (hex, a) => {
  const n = parseInt(hex, 16);
  const c = `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`;
  return a === undefined ? `#${hex}` : `rgb(${c} / ${a})`;
};
const esc = (c) => c.replace(/([^a-zA-Z0-9_-])/g, '\\$1');

const rules = [];
for (const [cls, m] of seen) {
  const [, variants, kind, hex, alpha] = m;
  const light = MAP[hex.toUpperCase()];
  if (!light) continue;
  if (variants.split(':').filter(Boolean).some((v) => !['hover', 'focus', 'active', 'placeholder'].includes(v))) continue;
  const a = alpha === undefined ? undefined : alpha.startsWith('[') ? alpha.slice(1, -1) : (Number(alpha) / 100).toString();
  const col = rgb(light, a);
  const transparent = rgb(light, 0);
  let sel = '.' + esc(cls);
  for (const v of variants.split(':').filter(Boolean)) sel += v === 'placeholder' ? '::placeholder' : ':' + v;
  let body;
  switch (kind) {
    case 'bg': body = `background-color:${col}`; break;
    case 'text': body = `color:${col}`; break;
    case 'border': body = `border-color:${col}`; break;
    case 'ring': body = `--tw-ring-color:${col}`; break;
    case 'from': body = `--tw-gradient-from:${col} var(--tw-gradient-from-position);--tw-gradient-to:${transparent} var(--tw-gradient-to-position);--tw-gradient-stops:var(--tw-gradient-from),var(--tw-gradient-to)`; break;
    case 'via': body = `--tw-gradient-to:${transparent} var(--tw-gradient-to-position);--tw-gradient-stops:var(--tw-gradient-from),${col} var(--tw-gradient-via-position),var(--tw-gradient-to)`; break;
    case 'to': body = `--tw-gradient-to:${col} var(--tw-gradient-to-position)`; break;
    case 'divide': sel += ' > :not([hidden]) ~ :not([hidden])'; body = `border-color:${col}`; break;
  }
  rules.push(`html[data-theme="light"] ${sel}{${body}}`);
}
rules.sort();

const head = `/* GENERATED by scripts/gen-light.cjs — do not edit. */
html[data-theme="light"]{color-scheme:light;
--neutral-900:#F6F7F9;--neutral-800:#FFFFFF;--neutral-700:#F2F4F7;--neutral-600:#EAECF0;--neutral-500:#D5D9E0;--neutral-400:#98A2B3;
--neutral-300:#475467;--neutral-100:#344054;--neutral-50:#101828;--neutral-border-hover:#AEB4C0;--brand-navy:#E4E7EC;--brand-blue:#D0D5DD;
--success:#15803D;--warning:#B45309;--danger:#C62828;--danger-text:#DC2626;--info:#2563EB;--los-dim:#98A2B3;--teal-text:#0F766E;
--pending:#6D28D9;--advisory:#9333EA;--sim:#7C3AED;
--surface-1:#FFFFFF;--surface-2:#F2F4F7;--hairline:#E4E7EC;--hairline-strong:#C7CCD6;
--edge-top:inset 0 1px 0 0 rgba(255,255,255,.6);--lift-1:0 1px 2px rgba(16,24,40,.06);--lift-2:0 8px 24px -8px rgba(16,24,40,.16);
--shadow-e1:0 1px 3px rgba(16,24,40,.1);--shadow-e2:0 8px 24px rgba(16,24,40,.12);--shadow-e3:0 16px 48px rgba(16,24,40,.16);}
html[data-theme="light"] .app-canvas{background-color:#F6F7F9}
html[data-theme="light"] .chrome-surface{background-color:#FFFFFF}
html[data-theme="light"] .label-caps{color:#667085}
html[data-theme="light"] .skeleton{background:linear-gradient(90deg,#EAECF0 25%,#F2F4F7 50%,#EAECF0 75%);background-size:200% 100%}
html[data-theme="light"] ::-webkit-scrollbar-thumb{background:#C7CCD6;background-clip:content-box}
html[data-theme="light"] ::selection{background:rgba(46,111,216,.22);color:#101828}
`;
fs.writeFileSync('src/styles/light.generated.css', head + rules.join('\n') + '\n');
console.log('light rules:', rules.length);
